apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: isodate-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: isodate-service
    spec:
      containers:
      - name: isodate-service
        image: chronos_isodate-service
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
